owner: kilobyteno
repo: status.kilobyte.no

assignees: DanielRTRD

sites:
  - name: kilobyte.no
    url: https://kilobyte.no
  - name: lanms.net
    url: https://lanms.net

status-website:
  name: "Kilobyte AS - Status"
  logoUrl: https://kilobyte.no/img/kilobyte_logo_dark.svg
  cname: status.kilobyte.no
  navbar:
    - title: Status
      href: /
    - title: kilobyte.no
      href: https://kilobyte.no

commitMessages:
  commitAuthorName: "Daniel S. Billing"
  commitAuthorEmail: "daniel@kilobyte.no"
