# Change these first
owner: kilobyteno # Your GitHub organization or username, where this repository lives
repo: status.kilobyte.no # The name of this repository

assignees: DanielRTRD

sites:
  - name: kilobyte.no
    url: https://kilobyte.no
  - name: lanms.net
    url: https://lanms.net
  - name: pokemon3d.net
    url: https://pokemon3d.net
  - name: karp.pokemon3d.net
    check: "tcp-ping"
    url: karp.pokemon3d.net
    port: 15124

status-website:
  name: "Kilobyte AS - Status"
  logoUrl: https://kilobyte.no/img/kilobyte_logo_dark.svg
  cname: status.kilobyte.no
  navbar:
    - title: Status
      href: /
    - title: kilobyte.no
      href: https://kilobyte.no

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
