# Change these first
owner: kilobyteno # Your GitHub organization or username, where this repository lives
repo: status.kilobyte.no # The name of this repository

assignees: DanielRTRD

sites:
  - name: kilobyte.no
    url: https://kilobyte.no

status-website:
  name: "status.kilobyte.no"
  baseUrl: /status.kilobyte.no
  logoUrl: https://kilobyte.no/img/kilobyte_logo_dark.svg
  introTitle: "Kilobyte AS - Status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
